server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wistyle?useSSL=false&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

mybatis:
  mapper-locations:
