server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo01?useSSL=false&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
#静态资源路径
file:
  upload-files:
    staticImgPath: /static/img/**
    staticBgmPath: /static/bgm/**
    staticVideoPath: /static/video/**
    uploadImgPath: E:/static/img/
    uploadBgmPath: E:/static/bgm/
    uploadVideoPath: E:/static/video/


mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zhiy.zy.domain
